# Generated by Django 2.2.4 on 2024-07-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240722_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
